"""
scenario_analysis.py
-----------------------
Generates best-case, worst-case, and most-likely scenario forecasts
by adjusting external regressors (e.g. economic indicators, trend signals).
"""

import logging
import pandas as pd

logging.basicConfig(level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


# Default multiplicative adjustments applied to each regressor per scenario.
# Tune these based on domain knowledge (e.g. unemployment +20% in worst case typically suppresses hiring demand).
DEFAULT_SCENARIOS = {
    "best_case": 0.85,
    "most_likely": 1.0,
    "worst_case": 1.20,
}


def build_scenario_future(prophet_df, future_template, regressor_cols, factor):
    """
    Apply a multiplicative factor to regressor columns in the future dataframe
    for rows beyond the historical data range.
    """

    future = future_template.copy()
    cutoff = prophet_df["ds"].max()

    for col in regressor_cols:
        last_value = prophet_df[col].iloc[-1]
        mask = future["ds"] > cutoff
        future.loc[mask, col] = last_value * factor
        future.loc[~mask, col] = prophet_df[col].reindex(
            future.index).fillna(last_value)

    return future


def run_prophet_scenarios(model, prophet_df, regressor_cols, periods=12, freq="ME",
                          scenarios=None):
    """
    Run scenario forecasts using a fitted Prophet model.

    Returns dict: scenario_name -> forecast DataFrame (ds, yhat, yhat_lower, yhat_upper)
    """

    scenarios = scenarios or DEFAULT_SCENARIOS
    base_future = model.make_future_dataframe(periods=periods, freq=freq)

    results = {}
    for name, factor in scenarios.items():
        future = build_scenario_future(
            prophet_df, base_future, regressor_cols, factor)
        forecast = model.predict(future)
        results[name] = forecast[["ds", "yhat", "yhat_lower", "yhat_upper"]]
        logger.info("Scenario '%s' (factor=%.2f): final forecast value = %.2f",
                    name, factor, forecast["yhat"].iloc[-1])

    return results


def combine_scenarios_to_df(scenario_results, value_col="yhat", date_col="ds"):
    """Combine multiple scenario forecasts into a single wide DataFrame for plotting."""

    combined = None

    for name, df in scenario_results.items():
        series = df.set_index(date_col)[value_col].rename(
            name) if date_col in df.columns else df.rename(name)
        if combined is None:
            combined = series.to_frame()
        else:
            combined = combined.join(series, how="outer")

    return combined


if __name__ == "__main__":
    import os
    import sys

    PARENT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

    sys.path.append(PARENT_DIR)  # Ensure parent dir is in path for imports

    from analysis.forecasting_models import train_prophet_model

    DATA_PROCESSED = os.path.join(PARENT_DIR, "data", "processed")
    FORECAST_DIR = os.path.join(PARENT_DIR, "predictions", "forecasts")

    os.makedirs(FORECAST_DIR, exist_ok=True)

    # Read the already-built merged features (generated by forecasting_models.py
    # or main.py's step_forecasting). This ensures scenarios use the same
    # demand series and regressors as the rest of the pipeline.
    merged = pd.read_csv(
        os.path.join(DATA_PROCESSED, "merged_features.csv"), index_col=0, parse_dates=True
    )
    regressor_candidates = [c for c in merged.columns if c != "y"][:5]

    model, prophet_df, used_regressors = train_prophet_model(
        merged, regressor_cols=regressor_candidates
    )
    scenario_results = run_prophet_scenarios(
        model, prophet_df, used_regressors, periods=12)

    combined = combine_scenarios_to_df(scenario_results)
    combined.to_csv(os.path.join(FORECAST_DIR, "scenario_forecasts.csv"))
    logger.info(
        "Saved scenario forecasts -> %s", os.path.join(FORECAST_DIR, "scenario_forecasts.csv"))
